### ISSUE TITLE
Add anonymous thread replies

### ISSUE THREAD

**Issue by Ulfingrad** [AmericanAirlines/AskingForAFriend#11]
### Pre-requisites:

- [x] Yes, I looked through both [open and closed issues](../../../issues?utf8=✓&q=is%3Aissue) looking for what I needed

## Feature Description

This feature will allow a user to use a shortcut in order to anonymously reply inside of a thread. A potential feature that could be added is adding a fake name based on the user (so that anonymous responses don't become confusing), but that would probably require adding a DB so that might have to broken off into a separate issue.

**Comment by SpencerKaiser** [comment]
Closed via #20
